# Site settings
title: Swiss Ski
client:
  name: SWISS
  link: https://www.swiss.com/unitedkingdom/EN/swiss-the-skiers-airline-lon
description: >
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
baseurl: "/swiss-ski" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [js/scripts.min.js]
sass:
    sass_dir: css
    style: compressed